"""TEST-10/11 — adversarial self-play: generate attacks the corpus does not contain, score the guard
on a held-out split, and propose a patch a human ratifies.

WHAT "SELF-PLAY" MEANS HERE, PRECISELY. This MUTATES the shipped corpus — recombining payloads,
re-encoding them, splitting one probe across a campaign — deterministically from a seed. It does not
invent attacks the way a model would. That is a deliberate trade, not a shortcut: the shipped
interpreter seam needs an API key and its tests skip without one, so an LLM-driven generator would be
the one red-team component that never runs in CI, which is the last place a safety check should be
absent. Mutation gives up creativity and buys a generator that runs on every commit, forever, with no
key and no network.

So the honest claim is "attacks the corpus does not contain", not "attacks nobody has thought of".
The module says so, and a test keeps it saying so.

NOTHING GENERATED IS EVER EXECUTED. Phase 12's rule, inherited without exception: every probe goes
through `evaluate(action) -> Decision`. A generator that invented new attacks AND ran them would be
building and firing novel exploits at a live deployment — the validation tool becoming the breach, and
worse than Phase 12's version because these inputs are ones nobody reviewed.

HELD-OUT SCORING, OR THE SCORE IS SELF-CONGRATULATION. A generator that proposes a patch and then
scores it on the attacks it just generated always succeeds. The generated set is SPLIT: patches are
proposed from `train` and scored on `holdout`, and a patch that only helps on train is reported as
NOT GENERALISING. Without this, TEST-10's "scores defenses" measures nothing.

A PATCH IS A POL-10 AMENDMENT. TEST-10 says human-ratified; TEST-11 says ratified defenses roll out.
Phase 13 built exactly that, including the guarantee that a pending proposal changes no decision.
Self-play proposes THROUGH it rather than beside it — a second way to change the rules would be a
second thing to attack, and the weaker one is the one that would be used.
"""

from __future__ import annotations

import base64
import random
from dataclasses import dataclass, field
from uuid import uuid4

from agentos_contract import ActionContext, ActionType, AgentAction

from agentos_sdk.redteam import BLOCKING_OUTCOMES, SUITES, Attack

# One generation run. Bounded because a caller picks the count and every generated probe costs a
# pipeline evaluation.
_MAX_GENERATED = 500


@dataclass(frozen=True)
class GeneratedAttack:
    """A mutated probe, and the corpus attack it descends from.

    `parent_id` is kept so a finding is traceable back to the seed attack — a novel probe nobody can
    trace is a bug report without a reproduction.
    """

    attack: Attack
    parent_id: str
    mutation: str


@dataclass(frozen=True)
class SelfPlayResult:
    """What a self-play round found, split so the score means something."""

    generated: int = 0
    train_blocked: int = 0
    train_total: int = 0
    holdout_blocked: int = 0
    holdout_total: int = 0
    slipped: tuple[str, ...] = ()
    generator: str = "mutation"

    @property
    def train_asr(self) -> float:
        return 0.0 if not self.train_total else (self.train_total - self.train_blocked) / self.train_total

    @property
    def holdout_asr(self) -> float:
        return (
            0.0
            if not self.holdout_total
            else (self.holdout_total - self.holdout_blocked) / self.holdout_total
        )

    @property
    def generalises(self) -> bool | None:
        """Whether the guard holds on attacks it was not tuned against.

        None when either split is empty: with nothing held out there is no generalisation claim to
        make, and returning True there would be the circularity this split exists to prevent.
        """
        if not self.train_total or not self.holdout_total:
            return None
        return self.holdout_asr <= self.train_asr + 1e-9

    def as_dict(self) -> dict:
        return {
            "generated": self.generated,
            "generator": self.generator,
            "train": {"total": self.train_total, "blocked": self.train_blocked,
                      "attack_success_rate": self.train_asr},
            "holdout": {"total": self.holdout_total, "blocked": self.holdout_blocked,
                        "attack_success_rate": self.holdout_asr},
            "generalises": self.generalises,
            "slipped": list(self.slipped),
            "note": (
                "Generated by MUTATING the shipped corpus, deterministically from a seed — these "
                "are attacks the corpus does not contain, not attacks nobody has thought of. "
                "Nothing here was executed; every probe went through the decision path only."
            ),
        }


def _obfuscate(text: str, rng: random.Random) -> str:
    """Re-encode a payload so a literal-substring detector misses it while intent survives."""
    choice = rng.randrange(3)
    if choice == 0:
        return " ".join(text)
    if choice == 1:
        return base64.b64encode(text.encode()).decode()
    return text.replace(" ", "​ ")  # zero-width joiner between words


def generate(seed: int = 0, count: int = 20, *, suites=None) -> list[GeneratedAttack]:
    """Mutate the corpus into `count` probes it does not contain.

    Deterministic in `seed`: a finding has to be reproducible, and a generator that cannot replay the
    probe that slipped produces bug reports nobody can act on.
    """
    rng = random.Random(seed)
    corpus = [
        (name, attack)
        for name, attacks in sorted((suites or SUITES).items())
        for attack in attacks
    ]
    if not corpus:
        return []
    out: list[GeneratedAttack] = []
    for i in range(min(int(count), _MAX_GENERATED)):
        suite, parent = corpus[rng.randrange(len(corpus))]
        payload = dict(parent.payload)
        mutation = rng.choice(("obfuscate", "recombine", "amplify"))
        if mutation == "obfuscate":
            for key in ("content", "messages"):
                if key in payload:
                    value = payload[key]
                    payload[key] = (
                        [_obfuscate(str(v), rng) for v in value]
                        if isinstance(value, list)
                        else _obfuscate(str(value), rng)
                    )
        elif mutation == "recombine":
            _, donor = corpus[rng.randrange(len(corpus))]
            for key in ("content", "messages"):
                if key in donor.payload and key in payload:
                    payload[key] = donor.payload[key]
        else:  # amplify — repeat the instruction, a common evasion of single-match heuristics
            for key in ("content", "messages"):
                if key in payload:
                    value = payload[key]
                    payload[key] = (
                        [f"{v} {v}" for v in value] if isinstance(value, list) else f"{value} {value}"
                    )
        out.append(
            GeneratedAttack(
                attack=Attack(
                    id=f"gen_{seed}_{i}_{mutation}",
                    suite=f"selfplay_{suite}",
                    action_type=parent.action_type,
                    target=parent.target,
                    payload=payload,
                ),
                parent_id=parent.id,
                mutation=mutation,
            )
        )
    return out


def split(generated: list[GeneratedAttack], *, holdout_fraction: float = 0.5):
    """Split into (train, holdout).

    The split is by POSITION on a deterministically generated list rather than by shuffling at score
    time, so the same seed always produces the same halves — a held-out set that moves between runs
    cannot support a claim about generalisation.
    """
    if not generated:
        return [], []
    cut = max(1, int(len(generated) * (1.0 - holdout_fraction)))
    return generated[:cut], generated[cut:]


async def run_selfplay(
    evaluate,
    *,
    agent_id: str,
    token: str,
    seed: int = 0,
    count: int = 20,
    holdout_fraction: float = 0.5,
) -> SelfPlayResult:
    """Generate, split, and score against the live DECISION path.

    `evaluate` is the same seam `run_suite` uses. Nothing here invokes a handler (spec D-4).
    """
    generated = generate(seed=seed, count=count)
    train, holdout = split(generated, holdout_fraction=holdout_fraction)
    slipped: list[str] = []

    async def _score(batch) -> int:
        blocked = 0
        for item in batch:
            action = AgentAction(
                agent_id=agent_id,
                type=item.attack.action_type,
                target=item.attack.target,
                payload=item.attack.payload,
                identity_token=token,
                context=ActionContext(conversation_id=str(uuid4())),
            )
            decision = await evaluate(action)
            if decision.outcome in BLOCKING_OUTCOMES:
                blocked += 1
            else:
                slipped.append(item.attack.id)
        return blocked

    train_blocked = await _score(train)
    holdout_blocked = await _score(holdout)
    return SelfPlayResult(
        generated=len(generated),
        train_blocked=train_blocked,
        train_total=len(train),
        holdout_blocked=holdout_blocked,
        holdout_total=len(holdout),
        slipped=tuple(slipped),
    )


def propose_patch(result: SelfPlayResult, constitution: dict, *, title: str | None = None) -> dict:
    """Turn a self-play finding into a POL-10 amendment PROPOSAL.

    Returns the argument dict for `AmendmentStore.propose` — deliberately not the amendment itself,
    and deliberately not calling it. Self-play does not get to write to the amendment store: it
    produces a proposal a caller submits, so the human ratification step Phase 13 built stays the only
    way a rule changes.

    Raises when nothing slipped. A patch proposed against a guard that held is noise in an operator's
    review queue, and a queue full of no-op proposals is how the one real proposal gets rubber-stamped.
    """
    if not result.slipped:
        raise ValueError(
            "nothing slipped: there is no defence to patch, and a no-op proposal in the review "
            "queue trains an operator to approve without reading"
        )
    return {
        "title": title or f"self-play: {len(result.slipped)} probe(s) slipped",
        "rationale": (
            f"Self-play generated {result.generated} probes by mutating the shipped corpus. "
            f"{len(result.slipped)} were NOT blocked: {', '.join(result.slipped[:10])}. "
            f"Train ASR {result.train_asr:.3f}, held-out ASR {result.holdout_asr:.3f}, "
            f"generalises={result.generalises}. "
            "These are mutations of known attacks, not novel classes — a human should confirm the "
            "proposed rule addresses the underlying weakness rather than the specific string."
        ),
        "proposed_by": "selfplay",
        "source": constitution,
    }


@dataclass
class ThreatIntel:
    """TEST-11 — externally sourced attack patterns, imported into the corpus.

    Imported patterns are attacker-supplied text from outside this deployment, so they are treated as
    exactly that: added as PROBES to run through the decision path, never as rules, never as anything
    executed. A feed that could add a rule would be a feed that could edit the constitution.
    """

    patterns: list[Attack] = field(default_factory=list)

    def import_patterns(self, entries, *, source: str) -> int:
        """Add external patterns. Returns how many were accepted."""
        if not (source or "").strip():
            raise ValueError("threat intel needs a source: an unattributed feed cannot be assessed")
        accepted = 0
        for entry in entries or []:
            try:
                name = str(entry["id"])
                payload = dict(entry["payload"])
            except (KeyError, TypeError, ValueError):
                continue  # a malformed entry is skipped, never guessed at
            self.patterns.append(
                Attack(
                    id=f"intel_{source}_{name}",
                    suite=f"threat_intel_{source}",
                    action_type=ActionType(entry.get("action_type", "tool_call")),
                    target=str(entry.get("target", "http_get")),
                    payload=payload,
                )
            )
            accepted += 1
        return accepted

    def as_suite(self) -> tuple[Attack, ...]:
        return tuple(self.patterns)
