# GENERATED by agentos-constitution — DO NOT EDIT.
# constitution_version: sha256:4f8698bb8543fab0d68105eddaed95e943a3122a61e4b685142a5b7a8d21049d
# policy_input_schema_version: 1
package agentos.constitution

import rego.v1

# Principle 1.1 — Egress allowlist
# An agent may only make outbound requests to allowlisted hosts.
matched contains {"principle_ref": "1.1", "effect": "deny"} if {
	input.type in {"tool_call"}
	not input.egress.host in data.lists.egress_allowlist
}

# Principle 2.1 — Destructive or exfiltrating intent requires approval
# Destructive or exfiltrating actions require human approval.
matched contains {"principle_ref": "2.1", "effect": "require_approval"} if {
	input.intent.class == "DATA_DESTRUCTION"
}

matched contains {"principle_ref": "2.1", "effect": "require_approval"} if {
	input.intent.class == "DATA_EXFILTRATION"
}

# Principle 3.2 — PII never leaves approved hosts
# An agent must never send user PII to a host outside the approved allowlist.
matched contains {"principle_ref": "3.2", "effect": "deny"} if {
	input.type in {"mcp_call", "tool_call"}
	input.guardrails.pii == true
	not input.egress.host in data.lists.egress_allowlist
}

# Principle 3.5 — Rename-then-drop is forbidden
# A rename followed by destruction of the renamed resource is forbidden, even when each step looks benign alone.
matched contains {"principle_ref": "3.5", "effect": "deny"} if {
	"3.5" in input.sequence.matched_refs
}

# Principle 5.1 — Non-GET-like writes to memory require approval
# Memory writes outside read-like operations require approval.
matched contains {"principle_ref": "5.1", "effect": "require_approval"} if {
	input.type in {"memory_access"}
	input.memory.operation != "read"
	input.memory.operation != "list"
}

result := {"matched": matched, "no_match": count(matched) == 0}
