# GENERATED by agentos-constitution — DO NOT EDIT.
# constitution_version: sha256:69d5c51453b6df5aef6598819904748e6ded829fb84f4b2e72adf739d78f557b
# policy_input_schema_version: 1
package agentos.constitution

import rego.v1

# Principle 1.1 — Egress allowlist
# An agent may only make outbound requests to allowlisted hosts.
matched contains {"principle_ref": "1.1", "effect": "deny"} if {
	input.type in {"tool_call"}
	not input.egress.host in data.lists.egress_allowlist
}

# Principle 2.1 — Destructive or exfiltrating intent requires approval
# Destructive or exfiltrating actions require human approval.
matched contains {"principle_ref": "2.1", "effect": "require_approval"} if {
	input.intent.class == "DATA_DESTRUCTION"
}

matched contains {"principle_ref": "2.1", "effect": "require_approval"} if {
	input.intent.class == "DATA_EXFILTRATION"
}

# Principle 3.2 — PII never leaves approved hosts
# An agent must never send user PII to a host outside the approved allowlist.
matched contains {"principle_ref": "3.2", "effect": "deny"} if {
	input.type in {"mcp_call", "tool_call"}
	input.guardrails.pii == true
	not input.egress.host in data.lists.egress_allowlist
}

# Principle 3.5 — Rename-then-drop is forbidden
# A rename followed by destruction of the renamed resource is forbidden, even when each step looks benign alone.
matched contains {"principle_ref": "3.5", "effect": "deny"} if {
	"3.5" in input.sequence.matched_refs
}

result := {"matched": matched, "no_match": count(matched) == 0}
